# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # CORE CONFIGURATION
          user: Pyenb
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          
          repositories_affiliations: owner
          # NOT WORKING
          repositories_skipped: |
            @use.patterns
            
            -HWR-Ubungen/*
            -HomelabKinau/*
          
          extras_css: |
            h1 {color: #8A2BE2;}
            h2 {color: #8A2BE2;}
            h3 {color: #F38CFE;}
          
          # ACHIEVEMENTS
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_limit: 6
          
          # INTRODUCTION
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # ISOCALENDAR
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # LANGUAGES
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_ignored: tex, css, html, c, perl, inno setup, javascript

          
          # LINES
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # MUSIC
          plugin_music: yes
          plugin_music_limit: 3
          plugin_music_mode: recent
          plugin_music_provider: spotify
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_user: ben_beletage
          plugin_music_played_at: no
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          
          # REPOSITORIES
          plugin_repositories: yes
          plugin_repositories_featured: Outlook-desktop-ad-blocker, fail2telegram
          plugin_repositories_order: featured
          
          # STACKOVERFLOW
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 1
          plugin_stackoverflow_lines: 0
          plugin_stackoverflow_lines_snippet: 0
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_user: 10079440
          
          # STARS
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_traffic: yes
          
          # WAKATIME
          plugin_wakatime: yes
          plugin_wakatime_user: Pyenb
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_token: ${{ secrets.WAKA }}
          
          # STEAM
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_sections: recently-played
          plugin_steam_user: "76561198220847360"
          plugin_steam_recent_games_limit: 1

          # LEETCODE
          plugin_leetcode: yes
          plugin_leetcode_user: Pyenb

  replace-colors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Replace main color
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'github-metrics.svg'
          search-text: '.name span:first-child{color:#58a6ff}'
          replacement-text: '.name span:first-child{color:#F38CFE}'
      
      - name: Replace secondary color
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'github-metrics.svg'
          search-text: '.name{display:flex;align-items:center;justify-content:space-between;font-size:14px;line-height:14px;color:#58a6ff}'
          replacement-text: '.name{display:flex;align-items:center;justify-content:space-between;font-size:14px;line-height:14px;color:#F38CFE}'