name: Replace Colors in SVG

on:
  push:
    branches:
      - main

jobs:
  replace-colors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Replace main color
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'github-metrics.svg'
          search-text: '.name span:first-child{color:#58a6ff}'
          replacement-text: '.name span:first-child{color:#F38CFE}'
      
      - name: Replace secondary color
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'github-metrics.svg'
          search-text: '.name{display:flex;align-items:center;justify-content:space-between;font-size:14px;line-height:14px;color:#58a6ff}'
          replacement-text: '.name{display:flex;align-items:center;justify-content:space-between;font-size:14px;line-height:14px;color:#F38CFE}'
